name: Deploy to Neocities
  # You may pin to the exact commit or the version.
  # uses: bcomnes/deploy-to-neocities@e3e555927c3daa5aecac7f4a8c78bca2eee47844
  uses: bcomnes/deploy-to-neocities@v1.1.13
  with:
    # Neocities API token for site to deploy to
    api_token: 
    # Local folder to deploy to neocities
    dist_dir: # default is public
    # Delete orphaned files on neocities that don't exist in distDir
    cleanup: 
    # A glob string that prevents matched files from ever being deleted.
    protected_files: # optional
